# workflow name
name: Release CI

# main branch on push, auto run
on: 
  push:
    branches:
      - main
      
jobs:
  build: 
    runs-on: ubuntu-latest 
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 16.x 
      uses: actions/setup-node@master
      with:
        node-version: "16.x"
    - name: Setup about-me Dependencies
      run: |
        npm install
        npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        token: ${{ secrets.ACCESS_TOKEN }}